dist: xenial
sudo: required

language: go
go: "1.12"

cache:
  directories:
    - /home/travis/.hugopkg/

before_install:
  - echo "Start Build for Hugo Blog, kmahyyg.github.io"

install:
  - bash ./.download-deps.sh
  - hugo version && go version

script:
  - hugo --gc

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_PERTKN
  on:
    branch: raw2
  target-branch: master
  fqdn: blog.kmahyyg.xyz
  project-name: kmahyyg.github.io
  committer-from-gh: true
  local-dir: public

after_deploy:
  - sleep 5 && curl -Lk http://filebin.kmahyyg.xyz/blogcron/yyg

notifications:
  webhooks:
    urls:
      - https://integrations.bonbotics.io/travis/webhook/McReXwoNYgeQzXAr10StqlRMROG9mkkwo61TkaJU9tE
    on_success: always
    on_failure: always
    on_start: never


